// Datos de letras sincronizadas con offset
const letrasCanciones = {
    "Ride - Twenty One Pilots": {
        offset: 23, // segundos de espera.
        lyrics: [
            { time: 0, text: "I just wanna stay in the sun where I find" },
            { time: 4, text: "I know it's hard sometimes" },
            { time: 7, text: "Pieces of peace in the sun's peace of mind" },
            { time: 10.5, text: "I know it's hard sometimes" },
            { time: 13, text: "Yeah, I think about the end just way too much" },
            { time: 16.5, text: "But it's fun to fantasize" },
            { time: 19.5, text: "On my enemies I wouldn't wish who I was" },
            { time: 23, text: "But it's fun to fantasize" },
            { time: 25.5, text: "oh, oh, oh, oh" },
            { time: 27, text: "oh, oh, oh, oh" },
            { time: 28.5, text: "I'm falling so I'm taking my time on my ride" },
            { time: 33.5, text: "oh, oh, oh, oh" },
            { time: 35, text: "I'm falling so I'm taking my time on my ride" },
            { time: 43, text: "takin' my time on my ride" },
            { time: 51, text: "I'd die for you thats easy to say" },
            { time: 55, text: "We have a list of people that we would take" },
            { time: 60, text: "A bullet for them, a bullet for you" },
            { time: 65, text: "A bullet for everybody in this room" },
            { time: 70, text: "But I don't seem to see many bullets coming through" },
            { time: 75, text: "See many bullets coming through" },
            { time: 80, text: "Metaphorically I'm the man" },
            { time: 85, text: "But literally I don't know what I'd do" },
            { time: 90, text: "I'd live for you and that's hard to do" },
            { time: 95, text: "Even harder to say when you know it's not true" },
            { time: 100, text: "Even harder to write when you know that tonight" },
            { time: 105, text: "There were people back home who tried talking to you" },
            { time: 110, text: "But then you ignored them still" },
            { time: 115, text: "All these questions they're for real" },
            { time: 115, text: "Like who would you live for?" },
            { time: 120, text: "Who would you die for?" },
            { time: 125, text: "And would you ever kill?" },
            { time: 130, text: "I'm falling so I'm taking my time on my ride" },
            { time: 135, text: "I'm falling so I'm taking my time on my ride" },
            { time: 140, text: "I've been thinking too much..." },
            { time: 145, text: "Help me" },
            { time: 150, text: "I'm falling so I'm taking my time on my ride" },
            { time: 155, text: "I'm falling so I'm taking my time!" },
            { time: 160, text: "Taking my time on my ride..." },
            { time: 165, text: "I've been thinking too much..." },
            { time: 170, text: "Help me" },
        ],
    },
    "Stressed Out - Twenty One Pilots": {
        offset: 16, // segundos de espera.
        lyrics: [
            { time: 0, text: "I wish I found some better sounds no one's ever heard" },
            { time: 3, text: "I wish I had a better voice that sang some better words" },
            { time: 6, text: "I wish I found some chords in an order that is new" },
            { time: 9, text: "I wish I didn't have to rhyme every time I sang" },
            { time: 12, text: "I was told when I get older, all my fears would shrink" },
            { time: 14, text:"But now I'm insecure, and I care what people think" },
            { time: 16.5, text: "My name's Blurryface and I care what you think" },
            { time: 21.5, text: "My name's Blurryface and I care what you think" },
            { time: 40, text: "Wish we could turn back time" },
            { time: 43.5, text: "To the good old days" },
            { time: 46, text: "When our mama sang us to sleep" },
            { time: 49, text: "But now we're stressed out (oh)" },
            { time: 51.5, text: "Wish we could turn back time (oh)" },
            { time: 54.5, text: "To the good old days (oh)" },
            { time: 57, text: "When our mama sang us to sleep" },
            { time: 60, text: "But now we're stressed out" },
            { time: 80, text:"We're stressed out" },
            { time: 85, text: "Sometimes a certain smell will take me back to when I was young" },
            { time: 90, text: "How come I'm never able to identify where it's coming from?" },
            { time: 95, text: "I'd make a candle out of it if I ever found it" },
            { time: 100, text: "Try to sell it, never sell out of it, I'd probably only sell one" },
            { time: 105, text: "It'd be to my brother, 'cause we have the same nose" },
            { time: 110, text: "Same clothes, homegrown, a stone's throw from a creek we to roam" },
            { time: 115, text: "But it would remind us of when nothing really mattered" },
            { time: 115, text: "Out of student loans and tree house homes, we all would take the latter" },
            { time: 120, text: "My name's Blurryface and I care what you think" },
            { time: 125, text: "My name's Blurryface and I care what you think" },
            { time: 130, text: "Wish we could turn back time" },
            { time: 135, text: "To the good old days" },
            { time: 140, text: "When our mama sang us to sleep" },
            { time: 145, text: "But now we're stressed out" },
            { time: 150, text: "Used to play pretend, give each other different names" },
            { time: 155, text: "We would build a rocket ship and then we'd fly it far away" },
            { time: 160, text: "Used to dream of outer space, but now they're laughing at our face, saying" },
            { time: 165, text: "Wake up, you need to make money, yeah" },
            { time: 170, text: "We used to play pretend, give each other different names" },
            { time: 175, text: "We would build a rocket ship and then we'd fly it far away" },
            { time: 180, text: "Used to dream of outer space, but now they're laughing at our face, saying" },
            { time: 185, text: "Wake up, you need to make money, yeah" },
            { time: 190, text: "Wish we could turn back time" },
            { time: 195, text: "To the good old days" },
            { time: 200, text: "When our mama sang us to sleep" },
            { time: 205, text: "But now we're stressed out (oh)" },
            { time: 210, text: "Wish we could turn back time (oh)" },
            { time: 215, text: "To the good old days (oh)" },
            { time: 220, text: "When our mama sang us to sleep" },
            { time: 220, text: "But now we're stressed out" },
            { time: 225, text: "We used to play pretend, used to play pretend, money" },
            { time: 230, text: "We used to play pretend, wake up, you need the money" },
            { time: 235, text: "Used to play pretend, used to play pretend, money" },
            { time: 240, text: "We used to play pretend, wake up, you need the money" },
            { time: 245, text: "Used to play pretend, give each other different names" },
            { time: 250, text: "We would build a rocket ship and then we'd fly it far away" },
            { time: 255, text: "Used to dream of outer space, but now they're laughing at our face, saying" },
            { time: 260, text: "Wake up, you need to make money, yeah" },
        ],
    },
    "Heathens - Twenty One Pilots": {
        offset: 21, // segundos de espera.
        lyrics: [
            { time: 0, text: "All my friends are heathens, take it slow" },
            { time: 5, text: "Wait for them to ask you who you know" },
            { time: 10, text: "Please don't make any sudden moves" },
            { time: 15, text: "You don't know the half of the abuse" },
            { time: 20, text: "All my friends are heathens, take it slow" },
            { time: 25, text:"Wait for them to ask you who you know" },
            { time: 30, text: "Please don't make any sudden moves" },
            { time: 35, text: "You don't know the half of the abuse" },
            { time: 40, text: "Welcome to the room of people" },
            { time: 45, text: "Who have rooms of people that they loved one day" },
            { time: 50, text: "Docked away" },
            { time: 55, text: "Just because we check the guns at the door" },
            { time: 60, text: "Doesn't mean our brains will change from hand grenades" },
            { time: 65, text: "You'll never know the psychopath sitting next to you" },
            { time: 70, text: "You'll never know the murderer sitting next to you" },
            { time: 75, text: "You'll think, How'd I get here, sitting next to you?" },
            { time: 80, text:"But after all I've said, please don't forget" },
            { time: 85, text: "All my friends are heathens, take it slow" },
            { time: 90, text: "Wait for them to ask you who you know" },
            { time: 95, text: "Please don't make any sudden moves" },
            { time: 100, text: "You don't know the half of the abuse" },
            { time: 105, text: "We don't deal with outsiders very well" },
            { time: 110, text: "They say newcomers have a certain smell" },
            { time: 115, text: "You have trust issues, not to mention" },
            { time: 115, text: "They say they can smell your intentions" },
            { time: 120, text: "You'll never know the freak show sitting next to you" },
            { time: 125, text: "You'll have some weird people sitting next to you" },
            { time: 130, text: "You'll think How did I get here, sitting next to you?" },
            { time: 135, text: "But after all I've said, please don't forget" },
            { time: 140, text: "(Watch it)" },
            { time: 145, text: "(Watch it)" },
            { time: 150, text: "All my friends are heathens, take it slow" },
            { time: 155, text: "Wait for them to ask you who you know" },
            { time: 160, text: "Please don't make any sudden moves" },
            { time: 165, text: "You don't know the half of the abuse" },
            { time: 170, text: "All my friends are heathens, take it slow (watch it)" },
            { time: 175, text: "Wait for them to ask you who you know (watch it)" },
            { time: 180, text: "Please all my friends are heathens, take it slow (watch it)" },
            { time: 185, text: "Wait for them to ask you who you know" },
            { time: 190, text: "Why'd you come? You knew you should have stayed" },
            { time: 195, text: "I tried to warn you just to stay away" },
            { time: 200, text: "And now they're outside ready to bust" },
            { time: 205, text: "It looks like you might be one of us" },
        ],
    },
    "Chlorine - Twenty One Pilots": {
        offset: 0, // segundos de espera.
        lyrics: [
            { time: 0, text: "So where are you?" },
            { time: 1, text: "It's been a little while" },
            { time: 17, text: "Sippin' on straight chlorine" },
            { time: 20, text: "Let the vibe slide over me" },
            { time: 21, text: "This beat is a chemical" },
            { time: 25, text: "Beat is a chemical" },
            { time: 27, text: "When I leave don't save my seat" },
            { time: 35, text: "I'll be back when it's all complete" },
            { time: 40, text: "The moment is medical" },
            { time: 45, text: "Moment is medical" },
            { time: 50, text: "Sippin' on straight chlorine" },
            { time: 55, text: "Lovin' what I'm tastin' (ooh)" },
            { time: 60, text: "Venom on my tongue" },
            { time: 65, text: "Dependent at times" },
            { time: 70, text: "Poisonous vibrations (ooh)" },
            { time: 75, text: "Help my body run" },
            { time: 80, text:"I'm runnin' for my life" },
            { time: 85, text: "Runnin' for my life" },
            { time: 90, text: "Sippin' on straight chlorine" },
            { time: 95, text: "Let the vibe slide over me" },
            { time: 100, text: "This beat is a chemical" },
            { time: 105, text: "Beat is a chemical" },
            { time: 110, text: "When I leave don't save my seat" },
            { time: 115, text: "I'll be back when it's all complete" },
            { time: 115, text: "The moment is medical" },
            { time: 120, text: "Moment is medical" },
            { time: 125, text: "Sippin' on straight chlorine" },
            { time: 130, text: "Fall out of formation (ooh)" },
            { time: 135, text: "I plan my escape" },
            { time: 140, text: "From walls they confined" },
            { time: 145, text: "Rebel red carnation (ooh)" },
            { time: 150, text: "Grows while I decay" },
            { time: 155, text: "I'm runnin' for my life" },
            { time: 160, text: "Runnin' for my life" },
            { time: 165, text: "Yeah, I'm running for my life" },
            { time: 170, text: "Runnin' for my life" },
            { time: 175, text: "Hide you in my coat pocket" },
            { time: 180, text: "Where I kept my rebel red" },
            { time: 185, text: "Felt I was invincible" },
            { time: 190, text: "You wrapped around my head" },
            { time: 195, text: "Now different lives I lead" },
            { time: 200, text: "My body lives on lead" },
            { time: 205, text: "The last two lines may read" },
            { time: 210, text: "Incorrect until said" },
            { time: 215, text: "The lead is terrible in flavor" },
            { time: 220, text: "But now you double as a papermaker" },
            { time: 255, text: "I despise you sometimes" },
            { time: 260, text: "I love to hate the fight" },
            { time: 265, text: "And you in my life is like" },
            { time: 270, text: "Sippin' on straight chlorine" },
            { time: 275, text: "Let the vibe slide over me" },
            { time: 280, text: "This beat is a chemical" },
            { time: 285, text: "Beat is a chemical" },
            { time: 290, text: "When I leave don't save my seat" },
            { time: 295, text: "I'll be back when it's all complete" },
            { time: 300, text: "The moment is medical" },
            { time: 305, text: "Moment is medical" },
            { time: 310, text: "Sippin' on straight chlorine" },
            { time: 315, text: "Let the vibe, let the vibe" },
            { time: 320, text: "Let the vibe, let the vibe" },
            { time: 325, text: "Beat is a chemical, yeah" },
            { time: 330, text: "Let the vibe, let the vibe" },
            { time: 335, text: "Let the vibe, let the vibe" },
            { time: 340, text: "The moment is medical, yeah" },
            { time: 345, text: "Sippin' on straight chlorine" },
            { time: 350, text: "Let the vibe, let the vibe" },
            { time: 355, text: "Let the vibe, let the vibe" },
            { time: 360, text: "Beat is a chemical, yeah" },
            { time: 365, text: "Let the vibe, let the vibe" },
            { time: 370, text: "Let the vibe, let the vibe" },
            { time: 375, text: "The moment is medical, yeah" },
            { time: 380, text: "I'm so sorry, I forgot you" },
            { time: 385, text: "Let me catch you up to speed" },
            { time: 390, text: "I've been tested like the ends of" },
            { time: 395, text: "A weathered flag that's by the sea" },
            { time: 400, text: "Can you build my house with pieces?" },
            { time: 405, text: "I'm just a chemical" },
            { time: 410, text: "Can you build my house with pieces?" },
            { time: 415, text: "I'm just a chemical" },
            { time: 420, text: "Can you build my house with pieces?" },
            { time: 425, text: "I'm just a chemical" },
            { time: 430, text: "Can you build my house with pieces?" },
            { time: 435, text: "I'm just a chemical" },
        ],
    },
    "Bones - Imagine Dragons": {
        offset: 4, // segundos de espera.
        lyrics: [
            { time: 0, text: "Gimme, gimme, gimme some time to think" },
            { time: 2.5, text: "I'm in the bathroom, looking at me" },
            { time: 4.5, text: "Facing the mirror is all I need" },
            { time: 8.5, text: "Wait until the reaper takes my life" },
            { time: 10.5, text: "Never gonna get me out alive" },
            { time: 12.5, text: "I will live a thousand million lives (ooh)" },
            { time: 16.5, text: "My patience is waning, is this entertaining?" },
            { time: 20.5, text: "Our patience is waning, is this entertaining?" },
            { time: 25, text: "I got this feeling, yeah, you know" },
            { time: 29, text: "Where I'm losing all control" },
            { time: 31, text: "Cause there's magic in my bones" },
            { time: 34, text: "I got this feeling in my soul" },
            { time: 37.5, text: "Go ahead and throw your stones" },
            { time: 39.5, text: "Cause there's magic in my bones" },
            { time: 42, text: "Playing with a stick of dynamite" },
            { time: 44.5, text: "There was never gray in black and white" },
            { time: 46, text: "There was never wrong 'til there was right (ooh, ah-ooh)" },
            { time: 50.5, text: "Feeling like a boulder hurtling" },
            { time: 52.5, text: "Seeing all the vultures circling" },
            { time: 55, text: "Burning in the flames I'm working in" },
            { time: 57, text: "Turning in a bed that's darkening" },
            { time: 59, text: "My patience is waning, is this entertaining?" },
            { time: 63, text: "Our patience is waning, is this entertaining?" },
            { time: 67.5, text: "I got this feeling, yeah, you know" },
            { time: 71, text: "Where I'm losing all control" },
            { time: 73, text: "Cause there's magic in my bones (in my bones)" },
            { time: 76, text: "I got this feeling in my soul" },
            { time: 79.5, text: "Go ahead and throw your stones" },
            { time: 81.5, text: "Cause there's magic in my bones" },
            { time: 89, text: "Cause there's magic in my bones" },
            { time: 92.5, text: "Look in the mirror of my mind" },
            { time: 94.5, text: "Turning the pages of my life" },
            { time: 96.5, text: "Walking the path so many paced a million times" },
            { time: 100.5, text: "Drown out the voices in the air" },
            { time: 102.5, text: "Leaving the ones that never cared" },
            { time: 104.5, text: "Picking the pieces up and building to the sky" },
            { time: 109.5, text: "My patience is waning, is this entertaining?" },
            { time: 113, text: "My patience is waning, is this entertaining?" },
            { time: 118, text: "I got this feeling, yeah, you know" },
            { time: 121.5, text: "Where I'm losing all control" },
            { time: 124, text: "Cause there's magic in my bones (magic in my bones)" },
            { time: 126.5, text: "I got this feeling in my soul" },
            { time: 130, text: "Go ahead and throw your stones (soul)" },
            { time: 132, text: "Cause there's magic in my bones" },
            { time: 133.5, text: "There goes my mind (I)" },
            { time: 135.5, text: "Don't mind" },
            { time: 225, text: "There goes my mind (there it goes, there it goes)" },
            { time: 230, text: "There goes my mind (I)" },
            { time: 235, text: "Don't mind (there it goes)" },
            { time: 240, text: "There goes my mind" },
            { time: 245, text: "Cause there's magic in my bones" },
        ],
    },
    "Believer - Imagine Dragons": {
        offset: 5, // segundos de espera.
        lyrics: [
            { time: 0, text: "First things first, I'ma say all the words inside my head" },
            { time: 5, text: "I'm fired up, and tired of the way that things have been, oh-ooh" },
            { time: 10, text: "The way that things have been, oh-ooh" },
            { time: 15, text: "Second thing second, don't you tell me what you think that I can be" },
            { time: 20, text: "I'm the one at the sail, I'm the master of my sea, oh-ooh" },
            { time: 25, text: "The master of my sea, oh-ooh" },
            { time: 30, text: "I was broken from a young age" },
            { time: 35, text: "Taking my sulking to the masses" },
            { time: 40, text: "Writing my poems for the few" },
            { time: 45, text: "That look at me, took to me, shook to me, feelin' me" },
            { time: 50, text: "Singing from heartache from the pain" },
            { time: 55, text: "Taking my message from the veins" },
            { time: 60, text: "Speaking my lesson from the brain" },
            { time: 65, text: "Seeing the beauty through the" },
            { time: 70, text: "Pain!" },
            { time: 75, text: "You made me a-, you made me a believer, believer" },
            { time: 80, text:"Pain!" },
            { time: 85, text: "You break me down, and build me up, believer, believer" },
            { time: 90, text: "Pain!" },
            { time: 95, text: "Oh, let the bullets fly, oh, let them rain" },
            { time: 100, text: "My life, my love, my drive it came from" },
            { time: 105, text: "Pain!" },
            { time: 110, text: "You made me a-, you made me a believer, believer" },
            { time: 115, text: "Third things third, send a prayer to the ones up above" },
            { time: 115, text: "All the hate that you've heard has turned your spirit to a dove, oh-" },
            { time: 120, text: "ooh" },
            { time: 125, text: "Your spirit up above, oh-ooh" },
            { time: 130, text: "I was choking in the crowd" },
            { time: 135, text: "Building my rain up in the cloud" },
            { time: 140, text: "Falling like ashes to the ground" },
            { time: 145, text: "Hoping my feelings, they would drown" },
            { time: 150, text: "But they never did, ever lived, ebbin' and flowin'" },
            { time: 155, text: "Inhibited, limited, 'til it broke open, and it rained down" },
            { time: 160, text: "It rained down like" },
            { time: 165, text: "Pain!" },
            { time: 170, text: "You made me a-, you made me a believer, believer" },
            { time: 175, text: "Pain!" },
            { time: 180, text: "You break me down, and build me up, believer, believer" },
            { time: 185, text: "Pain!" },
            { time: 190, text: "Oh, let the bullets fly, oh, let them rain" },
            { time: 195, text: "My life, my love, my drive it came from" },
            { time: 200, text: "Pain!" },
            { time: 205, text: "You made me a-, you made me a believer, believer" },
            { time: 210, text: "Last things last, by the grace of the fire and the flames" },
            { time: 215, text: "You're the face of the future, the blood in my veins, oh-ooh" },
            { time: 220, text: "The blood in my veins, oh-ooh" },
            { time: 225, text: "But they never did, ever lived, ebbin' and flowin'" },
            { time: 230, text: "Inhibited, limited, 'til it broke open, and it rained down" },
            { time: 235, text: "It rained down like" },
            { time: 240, text: "Pain!" },
            { time: 245, text: "You made me a-, you made me a believer, believer" },
            { time: 250, text: "Pain!" },
            { time: 255, text: "You break me down, and build me up, believer, believer" },
            { time: 260, text: "Pain!" },
            { time: 265, text: "Oh, let the bullets fly, oh, let them rain" },
            { time: 270, text: "My life, my love, my drive it came from" },
            { time: 275, text: "Pain!" },
            { time: 280, text: "You made me a-, you made me a believer, believer" },
        ],
    },
    "Thunder - Imagine Dragons": {
        offset: 23, // segundos de espera.
        lyrics: [
            { time: 0, text: "Just a young gun with a quick fuse" },
            { time: 2.5, text: "I was uptight, wanna let loose" },
            { time: 5.5, text: "I was dreaming of bigger things and" },
            { time: 8, text: "Wanna leave my own life behind" },
            { time: 11, text: "Not a Yes, sir, not a follower" },
            { time: 14, text: "Fit the box, fit the mold, have a seat" },
            { time: 16.5, text: "In the foyer, take a number" },
            { time: 19, text: "I was lightning before the thunder (thunder)" },
            { time: 22.5, text: "Thunder, thunder, thun-" },
            { time: 24.5, text: "Thunder, th-th-thunder, thunder" },
            { time: 27, text: "Thunder, thunder, thun-" },
            { time: 30, text: "Thunder, th-th-thunder, thunder" },
            { time: 33, text: "Thunder, feel the thunder (thun-, thun-)" },
            { time: 36.5, text: "Lightning then the thunder (th-th-thunder, thunder)" },
            { time: 39.5, text: "Thunder, feel the thunder (thun-, thun-)" },
            { time: 42.5, text: "Lightning then the thunder, thunder (th-th-thunder, thunder)" },
            { time: 47.5, text:"Thunder" },
            { time: 85, text: "Thunder" },
            { time: 90, text: "Kids were laughing in my classes" },
            { time: 95, text: "While I was scheming for the masses" },
            { time: 100, text: "Who do you think you are?" },
            { time: 105, text: "Dreaming 'bout being a big star" },
            { time: 110, text: "They say, You're basic, they say, You're easy" },
            { time: 115, text: "You're always riding in the back seat" },
            { time: 115, text: "Now I'm smiling from the stage while" },
            { time: 120, text: "You were clapping in the nosebleeds" },
            { time: 125, text: "Thunder, thunder, thun-" },
            { time: 130, text: "Thunder, th-th-thunder, thunder" },
            { time: 135, text: "Thunder, thunder, thun-" },
            { time: 140, text: "Thunder, th-th-thunder, thunder" },
            { time: 145, text: "Thunder, feel the thunder (thun-, thun-)" },
            { time: 150, text: "Lightning then the thunder (th-th-thunder, thunder)" },
            { time: 155, text: "Thunder, feel the thunder (thun-, thun-)" },
            { time: 160, text: "Lightning then the thunder, thunder (th-th-thunder)" },
            { time: 165, text: "Thunder, feel the thunder" },
            { time: 170, text: "Lightning then the thunder, thunder" },
            { time: 175, text: "Thunder, feel the thunder (thun-, thun-)" },
            { time: 180, text: "Lightning then the thunder, thunder (th-th-thunder, thunder)" },
            { time: 185, text: "Thunder, feel the thunder (thun-, thun-)" },
            { time: 190, text: "Lightning then the thunder, thunder (th-th-thunder)" },
            { time: 195, text: "Thunder, feel the thunder (never give up, never give up)" },
            { time: 200, text: "Lightning then the thunder, thunder (never give up on your dreams)" },
            { time: 205, text: "Thunder, feel the thunder (never give up, never give up)" },
            { time: 210, text: "Lightning then the thunder, thunder (never give up on your dreams)" },
            { time: 215, text: "Thunder, thunder, thun-" },
            { time: 220, text: "Thunder, th-th-thunder, thunder" },
            { time: 225, text: "Thunder, thunder, thun-" },
            { time: 230, text: "Thunder, th-th-thunder, thunder" },
            { time: 235, text: "(Whoa-oh-oh) thunder, thunder, thun-" },
            { time: 240, text: "Thunder, th-th-thunder, thunder" },
            { time: 245, text: "(Whoa-oh-oh) thunder, thunder, thun-" },
            { time: 250, text: "Thunder, th-th-thunder, thunder" },
        ],
    },
    "(You Drive Me) Crazy - Britney Spears": {
        offset: 14,
        lyrics: [
            { time: 0, text: "Baby, I'm so into you" },
            { time: 5, text: "You got that somethin', what can I do?" },
            { time: 10, text: "Baby, you spin me around" },
            { time: 15, text: "The earth is movin', but I can't feel the ground" },
            { time: 20, text: "Every time you look at me" },
            { time: 25, text: "My heart is jumpin', it's easy to see" },
            { time: 30, text: "Lovin' you mean so much more" },
            { time: 35, text: "More than anythin' I ever felt before" },
            { time: 40, text: "You drive me crazy, I just can't sleep" },
            { time: 45, text: "I'm so excited, I'm in too deep" },
            { time: 50, text: "Ooh, crazy, but it feels alright" },
            { time: 55, text: "Baby, thinkin' of you keeps me up all night" },
            { time: 60, text: "Ooh" },
            { time: 65, text: "Tell me you're so into me" },
            { time: 70, text: "That I'm the only one, you will see" },
            { time: 75, text: "Tell me I'm not in the blue, oh" },
            { time: 80, text: "That I'm not wastin' my feelings on you" },
            { time: 85, text: "Lovin' you means so much more" },
            { time: 90, text: "More than anythin' I ever felt before" },
            { time: 95, text: "You drive me crazy, I just can't sleep" },
            { time: 100, text: "I'm so excited, I'm in too deep" },
            { time: 105, text: "Ooh, crazy, but it feels alright" },
            { time: 110, text: "Baby, thinkin' of you keeps me up all night" },
            { time: 115, text: "Crazy, I just can't sleep" },
            { time: 120, text: "I'm so excited, I'm in too deep" },
            { time: 125, text: "Crazy, but it feels alright" },
            { time: 130, text: "Every day and every night" },
            { time: 135, text: "You drive me crazy (you drive me crazy, baby)" },
            { time: 140, text: "I'm so excited, I'm in too deep" },
            { time: 145, text: "Ooh, crazy (you make me feel alright)" },
            { time: 150, text: "Baby, thinkin' of you keeps me up all night (oh)" },
            { time: 155, text: "You drive me crazy (you drive me crazy, baby, yeah)" },
            { time: 160, text: "Oh, crazy, but it feels alright" },
            { time: 165, text: "Baby, thinkin' of you keeps me up all night" },
            { time: 170, text: "Baby, thinkin' of you keeps me up all night" },
        ],
    },
    "...Baby One More Time - Britney Spears": {
        offset: 18,
        lyrics: [
            { time: 0, text: "Oh, baby, baby" },
            { time: 5, text: "Oh, baby, baby" },
            { time: 10, text: "Oh, baby, baby, how was I supposed to know" },
            { time: 15, text: "That something wasn't right here?" },
            { time: 20, text: "Oh, baby, baby, I shouldn't have let you go" },
            { time: 25, text: "And now you're out of sight, yeah" },
            { time: 30, text: "Show me how you want it to be, tell me, baby" },
            { time: 35, text: "'Cause I need to know now, oh, because" },
            { time: 40, text: "My loneliness is killin' me (and I)" },
            { time: 45, text: "I must confess, I still believe (still believe)" },
            { time: 50, text: "When I'm not with you, I lose my mind, give me a sign" },
            { time: 55, text: "Hit me, baby, one more time" },
            { time: 60, text: "Oh, baby, baby, the reason I breathe is you (oh, yeah)" },
            { time: 65, text: "Boy, you got me blinded" },
            { time: 70, text: "Oh, pretty baby, there's nothing that I wouldn't do" },
            { time: 75, text: "It's not the way I planned it" },
            { time: 80, text: "Show me how you want it to be, tell me, baby" },
            { time: 85, text: "'Cause I need to know now, oh, because" },
            { time: 90, text: "My loneliness is killin' me (and I)" },
            { time: 95, text: "I must confess, I still believe (still believe)" },
            { time: 100, text: "When I'm not with you, I lose my mind, give me a sign" },
            { time: 105, text: "Hit me, baby, one more time" },
            { time: 110, text: "Oh, baby, baby (oh-oh)" },
            { time: 115, text: "Oh, baby, baby (eh-eh-yeah)" },
            { time: 120, text: "Oh, baby, baby, how was I supposed to know?" },
            { time: 125, text: "Oh, pretty baby, I shouldn't have let you go" },
            { time: 130, text: "I must confess that my loneliness is killin' me now" },
            { time: 135, text: "Don't you know I still believe" },
            { time: 140, text: "That you will be here, and give me a sign?" },
            { time: 145, text: "Hit me, baby, one more time" },
            { time: 150, text: "My loneliness is killin' me (and I)" },
            { time: 155, text: "I must confess, I still believe (still believe)" },
            { time: 160, text: "When I'm not with you, I lose my mind, give me a sign" },
            { time: 165, text: "Hit me, baby, one more time" },
            { time: 170, text: "I must confess that my loneliness is killin' me now" },
            { time: 175, text: "Don't you know I still believe" },
            { time: 180, text: "That you will be here, and give me a sign?" },
            { time: 185, text: "Hit me, baby, one more time" },
        ],
    },
    "Toxic - Britney Spears": {
        offset: 14, // segundos de espera.
        lyrics: [
            { time: 0, text: "Baby, can't you see I'm calling?" },
            { time: 5, text: "A guy like you should wear a warning" },
            { time: 10, text: "It's dangerous, I'm falling" },
            { time: 15, text: "There's no escape, I can't wait" },
            { time: 20, text: "I need a hit, baby, give me it" },
            { time: 25, text: "You're dangerous, I'm loving it" },
            { time: 30, text: "Too high, can't come down" },
            { time: 35, text: "Losing my head, spinnin' 'round and 'round" },
            { time: 40, text: "Do you feel me now?" },
            { time: 45, text: "With a taste of your lips, I'm on a ride" },
            { time: 50, text: "You're toxic, I'm slippin' under" },
            { time: 55, text: "With a taste of a poison paradise" },
            { time: 60, text: "I'm addicted to you" },
            { time: 65, text: "Don't you know that you're toxic?" },
            { time: 70, text: "And I love what you do" },
            { time: 75, text: "Don't you know that you're toxic?" },
            { time: 80, text:"It's getting late to give you up" },
            { time: 85, text: "I took a sip from my devil's cup" },
            { time: 90, text: "Slowly, it's taking over me" },
            { time: 95, text: "Too high, can't come down" },
            { time: 100, text: "It's in the air and it's all around" },
            { time: 105, text: "Can you feel me now?" },
            { time: 110, text: "With a taste of your lips, I'm on a ride" },
            { time: 115, text: "You're toxic, I'm slippin' under" },
            { time: 115, text: "With a taste of a poison paradise" },
            { time: 120, text: "I'm addicted to you" },
            { time: 125, text: "Don't you know that you're toxic?" },
            { time: 130, text: "And I love what you do" },
            { time: 135, text: "Don't you know that you're toxic?" },
            { time: 140, text: "Don't you know that you're toxic?" },
            { time: 145, text: "Taste of your lips, I'm on a ride" },
            { time: 150, text: "You're toxic, I'm slippin' under" },
            { time: 155, text: "With a taste of a poison paradise" },
            { time: 160, text: "I'm addicted to you" },
            { time: 165, text: "Don't you know that you're toxic?" },
            { time: 170, text: "With a taste of your lips, I'm on a ride" },
            { time: 175, text: "You're toxic, I'm slippin' under (toxic)" },
            { time: 180, text: "With a taste of a poison paradise" },
            { time: 185, text: "I'm addicted to you" },
            { time: 190, text: "Don't you know that you're toxic?" },
            { time: 195, text: "Intoxicate me now, with your lovin' now" },
            { time: 200, text: "I think I'm ready now, I think I'm ready now" },
            { time: 205, text: "Intoxicate me now, with your lovin' now" },
            { time: 210, text: "I think I'm ready now" },
        ],
    },
    "Ma Meilleure Ennemie - Stromae, Pomme": {
        offset: 11, // segundos de espera.
        lyrics: [
            { time: 0, text: "T'es la meilleure chose qui m'est arrivée" },
            { time: 2, text: "Mais aussi la pire chose qui m'est arrivée" },
            { time: 5, text: "Ce jour où je t'ai rencontrée, j'aurais peut-être préféré" },
            { time: 8, text: "Que ce jour soit jamais arrivé (arrivé)" },
            { time: 11, text: "La pire des bénédictions" },
            { time: 13, text: "La plus belle des malédictions" },
            { time: 15, text: "De toi, j'devrais m'éloigner" },
            { time: 17, text: "Mais comme dit le dicton" },
            { time: 18.5, text: "Plutôt qu'être seul, mieux vaut être mal accompagné" },
            { time: 21, text: "Tu sais c'qu'on dit" },
            { time: 24.8, text: "Soit près d'tes amis les plus chers" },
            { time: 27, text: "Mais aussi" },
            { time: 30, text: "Encore plus près d'tes adversaires" },
            { time: 32, text: "Mais ma meilleure ennemie, c'est toi" },
            { time: 35, text: "Fuis-moi, le pire, c'est toi et moi" },
            { time: 43, text: "Mais si tu cherches encore ma voix" },
            { time: 46, text:"Oublie-moi, le pire, c'est toi et moi" },
            { time: 55, text: "Pourquoi ton prénom me blesse" },
            { time: 59, text: "Quand il se cache juste là dans l'espace?" },
            { time: 65.5, text: "C'est quelle émotion, ta haine" },
            { time: 70, text: "Ou de la douceur" },
            { time: 72.5, text: "Quand j'entends ton prénom" },
            { time: 76.5, text: "Je t'avais dit ne regarde pas en arrière" },
            { time: 82, text: "Le passé qui te suit, te fait la guerre" },
            { time: 86.5, text: "Mais ma meilleure ennemie, c'est toi" },
            { time: 89.5, text: "Fuis-moi, le pire, c'est toi et moi" },
            { time: 97.5, text: "Mais ma meilleure ennemie, c'est toi" },
            { time: 100.5, text: "Fuis-moi, le pire, c'est toi et moi" },
        ],
    },
};