// Información de las canciones
const detallesCanciones = [
    {
      titulo: "Ride",
      artista: "Twenty One Pilots",
      imagen: "imagen/Blurryface.jpg",
      album: "Blurryface",
      duracion: "3:34",
      genero: "Alternative Rock",
      año: 2015,
      popularidad: "1528 M de reproducciones en youtube",
      recomendaciones: ["Stressed Out", "Heathens", "Chlorine"],
      fuente: "videos/Ride - Twenty One Pilots.mp4",
    },
    {
      titulo: "Stressed Out",
      artista: "Twenty One Pilots",
      imagen: "imagen/Blurryface.jpg",
      album: "Blurryface",
      duracion: "3:46",
      genero: "Electronic, Hip Hop, Rock",
      año: 2015,
      popularidad: "2967 M de reproducciones en youtube",
      recomendaciones: ["Ride", "Heathens", "Chlorine"],
      fuente: "videos/Stressed Out - Twenty One Pilots.mp4",
    },
    {
      titulo: "Heathens",
      artista: "Twenty One Pilots",
      imagen: "imagen/Heathens.jpg",
      album: "Heathens",
      duracion: "3:15",
      genero: "Thrash metal",
      año: 2016,
      popularidad: "2213 M de reproducciones en youtube",
      recomendaciones: ["Ride", "Stressed Out", "Chlorine"],
      fuente: "videos/Heathens - Twenty One Pilots.mp4",
    },
    {
      titulo: "Chlorine",
      artista: "Twenty One Pilots",
      imagen: "imagen/trench.jpg",
      album: "Trench",
      duracion: "5:24",
      genero: "Reggae",
      año: 2018,
      popularidad: "590 M de reproducciones en youtube",
      recomendaciones: ["Ride", "Stressed Out", "Heathens"],
      fuente: "videos/Chlorine - Twenty One Pilots.mp4",
    },
    {
      titulo: "Bones",
      artista: "Imagine Dragons",
      imagen: "imagen/Mercury - Act 2.jpg",
      album: "Mercury - Act 2",
      duracion: "2:45",
      genero: "Pop Rock",
      año: 2022,
      popularidad: "345 M de reproducciones en youtube",
      recomendaciones: ["Beliver", "Thunder"],
      fuente: "videos/Bones - Imagine Dragons.mp4",
    },
    {
      titulo: "Believer",
      artista: "Imagine Dragons",
      imagen: "imagen/evolve.jpg",
      album: "Evolve",
      duracion: "3:24",
      genero: "Pop Rock",
      año: 2017,
      popularidad: "2739 M de reproducciones en youtube",
      recomendaciones: ["Bones", "Thunder"],
      fuente: "videos/Believer - Imagine Dragons.mp4",
    },
    {
      titulo: "Thunder",
      artista: "Imagine Dragons",
      imagen: "imagen/evolve.jpg",
      album: "Evolve",
      duracion: "3:07",
      genero: "Pop Rock",
      año: 2017,
      popularidad: "2201 M de reproducciones en youtube",
      recomendaciones: ["Bones", "Believer"],
      fuente: "videos/Thunder - Imagine Dragons.mp4",
    },
    {
      titulo: "(You Drive Me) Crazy",
      artista: "Britney Spears",
      imagen: "imagen/bomt.jpg",
      album: "…Baby One More Time",
      duracion: "3:17",
      genero: "Pop",
      año: 1999,
      popularidad: "216 M de reproducciones en youtube",
      recomendaciones: ["…Baby One More Time", "Toxic"],
      fuente: "videos/(You Drive Me) Crazy - Britney Spears.mp4",
    },
    {
      titulo: "...Baby One More Time",
      artista: "Britney Spears",
      imagen: "imagen/bomt.jpg",
      album: "…Baby One More Time",
      duracion: "3:57",
      genero: "Pop",
      año: 1999,
      popularidad: "1000 M de reproducciones en youtube",
      recomendaciones: ["(You Drive Me) Crazy", "Toxic"],
      fuente: "videos/Baby One More Time - Britney Spears.mp4",
    },
    {
      titulo: "Toxic",
      artista: "Britney Spears",
      imagen: "imagen/InTheZone.jpg",
      album: "In The Zone",
      duracion: "3:18",
      genero: "Pop",
      año: 2003,
      popularidad: "693 M de reproducciones en youtube",
      recomendaciones: ["(You Drive Me) Crazy", "...Baby One More Time"],
      fuente: "videos/Toxic - Britney Spears.mp4",
    },
    {
      titulo: "Ma Meilleure Ennemie",
      artista: "Stromae, Pomme",
      imagen: "imagen/lolsito.jpg",
      album: "Arcane League of Legends: Season 2 (Soundtrack from the Animated Series)",
      duracion: "3:34",
      genero: "Alternative Rock",
      año: 2024,
      popularidad: "55 M de reproducciones en spotify",
      recomendaciones: ["To Ashes and Blood", "Come Play", "Pain The Town Blue", "En fin.. todo el album"],
      fuente: "videos/Ma Meilleure Ennemie - Stromae, Pomme.mp4",
    },
  ];